# Site settings
title: VCD7: Interaction Design
email: shuyang.li.95@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Shuyang's blog for VCD7: Interaction Design, built with <3 using Jekyll and served thru GitHub Pages.
baseurl: "/vcd7" # the subpath of your site, e.g. /blog/
url: "http://shuyang.li" # the base hostname & protocol for your site
twitter_username: shuyangl
github_username:  shuyangli
google_analytics:

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5